spring:
  application:
    name: hdmsam

  datasource:
    url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.hcbqigtjgwqcgwpmijrl
    password: "uRH6e3S92EZItf84"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: 8080
vaadin:
  allowed-packages: br.com.crmHdmSamBackend
  productionMode: true
  launch-browser: true
  level:
    com:
      vaadin: INFO


logging:
  level:
    br.com.crmhdmSamBackend: DEBUG
    org.springframework.security: DEBUG
